### ISSUE TITLE
Add support to use inline SVG as a layer source.

### ISSUE THREAD

**Issue by hbmueller** [hbmuller/rush-js#2]
Inline SVG can easily be turned into a string and converted into a data URI. Which then can be used as and image `src` [as mentioned here](https://css-tricks.com/lodge/svg/09-svg-data-uris). Eg.:
```js
const svgString = document.querySelector('.my-inline-svg').outerHTML;
const dataURI = `data:image/svg+xml;utf8,${svgString}`;
document.querySelector('.my-image').src = dataURI;
```
So it is probably possible to draw it to canvas as well. Adding support to have `Layer` accept inline SVGs as their source should be just a matter of making it abstract that over as a layer's `imageSrc`.

**Comment by KartikSoneji** [comment]
I have added inline SVG support as the source element in Layer. Please have a look.

**Comment by hbmueller** [comment]
Hey @KartikSoneji. Thanks for the contribution. I'll check it tonight.
