### ISSUE TITLE
Improving tooling and moving to typescript

### ISSUE THREAD

**Issue by hbmueller** [hbmuller/rush-js#3]
It would be very beneficial to adopt typescript as it could simplify the validation logic in the setters very much and make the library way easier to use.
That would probably include an update in the tooling config involved. So, maybe also moving to [rollup.js](https://rollupjs.org) would make things easier to handle.

**Comment by dshubhadeep** [comment]
@hbmuller Hi, I would like to work on this

**Comment by hbmueller** [comment]
@dshubhadeep Sure thing. Go ahead. Let me know if you have any questions and just make sure to keep docs up to date if you make any significant changes.

**Comment by dshubhadeep** [comment]
Are there any specific tsconfig options that are required for the package or a generic one will do ?
I'm also getting an error due to this [# symbol](https://github.com/hbmuller/philately/blob/master/src/Layer.js#L12) . We can use `private` fields in TS to resolve this.

**Comment by hbmueller** [comment]
I think a generic one is better. If there is any popular, well maintained one, even better.
About the "#" symbol, that is exactly the type of thing I was thinking TS would be good for. Feel free to replace it with a TS feature.
